Repository green-code-initiative/creedengo-php, pull requests merged in 2023-12, with the labels that each got.

#14 [ISSUE 13] add build number + clean sonar-packaging-maven-plugin
  CHANGELOG.md
  pom.xml
Labels: :beginner: good first issue, :syringe: bug

#10 EC34 replaced by EC35 : PHP implementation
  CHANGELOG.md
  src/main/java/fr/greencodeinitiative/php/PhpRuleRepository.java
  src/main/java/fr/greencodeinitiative/php/checks/AvoidTryCatchWithFileOpenedCheck.java
  src/test/java/fr/greencodeinitiative/php/checks/AvoidTryCatchFinallyCheckNOKfailsAllTryStatementsTest.java
  src/test/java/fr/greencodeinitiative/php/checks/AvoidTryCatchWithFileOpenedCheckTest.java
  src/test/resources/checks/AvoidTryCatchFinallyCheck_NOK_FailsAllTryStatements.php
  src/test/resources/checks/AvoidTryCatchWithFileOpenedCheck.php
Labels: :building_construction: refactoring, :card_file_box: rule

#15 Fix execution of unit tests with Maven
  CHANGELOG.md
  pom.xml
  src/test/java/fr/greencodeinitiative/php/checks/AvoidDoubleQuoteCheckTest.java
  src/test/java/fr/greencodeinitiative/php/checks/AvoidFullSQLRequestCheckTest.java
  src/test/java/fr/greencodeinitiative/php/checks/AvoidGettingSizeCollectionInLoopTest.java
  src/test/java/fr/greencodeinitiative/php/checks/AvoidMultipleIfElseStatementCheckTest.java
  src/test/java/fr/greencodeinitiative/php/checks/AvoidSQLRequestInLoopCheckTest.java
  src/test/java/fr/greencodeinitiative/php/checks/AvoidTryCatchWithFileOpenedCheckTest.java
  src/test/java/fr/greencodeinitiative/php/checks/AvoidUsingGlobalVariablesCheckTest.java
  src/test/java/fr/greencodeinitiative/php/checks/IncrementCheckTest.java
  src/test/java/fr/greencodeinitiative/php/checks/NoFunctionCallWhenDeclaringForLoopTest.java
  src/test/java/fr/greencodeinitiative/php/checks/UseOfMethodsForBasicOperationsTest.java
Labels: :building_construction: refactoring, :syringe: bug
